/***SCRIPT 750 STARTS HERE  ***/
/*** CREATED BY JAYESH STARTS ***/
/*** PURPOSE: SPR#105463 ***/
/*** DATE: 16/07/2021 TIME: 15:10 PM ***/
ALTER TABLE DEAL
ADD QUANTITY FLOAT DEFAULT(0.0)
GO
UPDATE DEAL SET QUANTITY=0 WHERE QUANTITY IS NULL
GO
/*** CREATED BY JAYESH ENDS***/

/***CREATED BY HITESH STARTS ***/
/***PURPOSE: Integration with Tracking World***/
/***DATE: 21/07/2021 TIME:18:07 ***/
ALTER TABLE DEFAULT_CONTROL3
ADD AVL_GPS_INTEGRATION CHAR(1) DEFAULT('N')
GO
UPDATE TABLE DEFAULT_CONTROL3
SET AVL_GPS_INTEGRATION='N' WHERE AVL_GPS_INTEGRATION IS NULL
GO
/***CREATED BY HITESH ENDS ***/
/***CREATED BY HITESH STARTS ***/
/***PURPOSE: Integration with Tracking World***/
/***DATE: 21/07/2021 TIME:18:07 ***/
CREATE TABLE VEHICLE_LINKING_LOG
(
UNIQUE_SEQ BIGINT IDENTITY(1,1) NOT NULL,
VEH_PLATE_NO VARCHAR(30) DEFAULT(' '),
CONTRACT_NO VARCHAR(15) DEFAULT(' '),
DATETIME VARCHAR(25) DEFAULT(' '),
LINK_UNLINK CHAR(1) DEFAULT('N'),
TUSER CHAR(10) DEFAULT(' '),
TDATE CHAR(8) DEFAULT('00000000'),
TTIME INTEGER DEFAULT(0)
)
GO
CREATE UNIQUE INDEX IDX_VEH_LINK_LOG ON VEHICLE_LINKING_LOG(VEH_PLATE_NO,CONTRACT_NO,DATETIME,LINK_UNLINK,TUSER,TDATE,TTIME)
/***CREATED BY HITESH ENDS ***/
/***CREATED BY HITESH STARTS ***/
/***PURPOSE: Integration with Tracking World***/
/***DATE: 23/07/2021 TIME:22:35 ***/
ALTER TABLE VEHICLE_LINKING_LOG
ADD RESULT INTEGER DEFAULT(0)
GO
UPDATE VEHICLE_LINKING_LOG
SET RESULT=0 WHERE RESULT IS NULL
GO
ALTER TABLE VEHICLE_LINKING_LOG
ADD UNIQUE_ID VARCHAR(50) DEFAULT(' ')
GO
UPDATE VEHICLE_LINKING_LOG
SET UNIQUE_ID=' ' WHERE RESULT IS NULL
GO
/***CREATED BY HITESH ENDS ***/
/*** CREEATED BY PRAFULL STARTS ***/
/*** PURPOSE: HERTZ DUBAI  - SUSCRIPTION MODULE CHANGES***/
/*** DATE: 15/07/2021  TIME:05:30  ***/
ALTER TABLE RES_IMPORT_NATIONAL
ADD ADDITIONAL_DRIVER FLOAT DEFAULT(0)
GO
UPDATE RES_IMPORT_NATIONAL
SET ADDITIONAL_DRIVER =0
WHERE ADDITIONAL_DRIVER IS NULL
GO
ALTER TABLE SUBSCRIPTION_PRICING
ADD DEDUCTIBLE FLOAT DEFAULT(0)
GO
UPDATE SUBSCRIPTION_PRICING
SET DEDUCTIBLE =0
WHERE DEDUCTIBLE IS NULL
GO
ALTER TABLE RES_INSURANCES_ALPHA_REF
ADD AMOUNT FLOAT DEFAULT(0)
GO
UPDATE RES_INSURANCES_ALPHA_REF
SET AMOUNT =0
WHERE AMOUNT IS NULL
GO
ALTER TABLE RES_EXTRAS
ADD AMOUNT FLOAT DEFAULT(0)
GO
UPDATE RES_EXTRAS
SET AMOUNT =0
WHERE AMOUNT IS NULL
GO
ALTER TABLE DEF_ADDITIONAL_FLAGS
ADD USE_BROKEN_DAYS CHAR(1) DEFAULT(' ')
GO
UPDATE DEF_ADDITIONAL_FLAGS
SET USE_BROKEN_DAYS =' '
WHERE USE_BROKEN_DAYS IS NULL
GO
/*** CREEATED BY PRAFULL ENDS ***/
/*** CREATED BY HITESH STARTS ***/
/*** PURPOSE: ESAL INVOICE PUSH CHANGES ***/
/*** DATE: 11/08/2021 TIME: 16:30 PM ***/
ALTER TABLE ESAL_INVOICE_HDR
ADD TO_PUSH CHAR(1) DEFAULT('N')
GO
UPDATE ESAL_INVOICE_HDR
SET TO_PUSH='N' WHERE TO_PUSH IS NULL
GO
ALTER TABLE ESAL_INVOICE_HDR
ADD PUSH_DATE CHAR(8) DEFAULT('00000000')
GO
UPDATE ESAL_INVOICE_HDR
SET PUSH_DATE='00000000' WHERE PUSH_DATE IS NULL
GO
ALTER TABLE ESAL_INVOICE_HDR
ADD PUSH_TIME INTEGER DEFAULT(0)
GO
UPDATE ESAL_INVOICE_HDR
SET PUSH_TIME=0 WHERE PUSH_TIME IS NULL
/*** CREATED BY HITESH ENDS***/
/*** CREATED BY OSAMAK STARTS***/
/** DATE: 11/08/2021 TIME: 03:00 PM **/
/** PURPOSE: HERTZ_SUBSCRIPTION **/
/* SQL */
CREATE TABLE AGREEMENT_TERMINATION_REQ
(
REQUEST_SEQ INTEGER IDENTITY(1,1),
INTERNET_RES_NO VARCHAR(25) DEFAULT(' '),
AGREEMENT_NO INTEGER DEFAULT(0),
CHECK_IN_DATE CHAR(8) DEFAULT(' '),
CHECK_IN_TIME INTEGER DEFAULT(0),
PENALTY_CHARGES FLOAT DEFAULT(0),
REQUEST_DATE CHAR(8) DEFAULT(' '),
REQUEST_TIME INTEGER DEFAULT(0),
CREATE_DATE CHAR(8) DEFAULT(' '),
CREATE_TIME INTEGER DEFAULT(0),
MODIFY_DATE CHAR(8) DEFAULT(' '),
MODIFY_TIME INTEGER DEFAULT(0),
CANCEL_DATE CHAR(8) DEFAULT(' '),
CANCEL_TIME INTEGER DEFAULT(0),
REQ_STATUS INTEGER DEFAULT(0)
)
GO

CREATE UNIQUE INDEX AGREEMENT_TERMINATION_REQ_IDX ON AGREEMENT_TERMINATION_REQ
(
AGREEMENT_NO,REQUEST_SEQ
)
GO
/*** CREATED BY NILESHC STARTS ***/
/*** PURPOSE: BUSINESS SOURCE AT CDP LEVEL  ***/
/*** DATE: 12/08/2021 TIME: 01:10 PM ***/
ALTER TABLE CDP
ADD BUSINESS_SOURCE SMALLINT DEFAULT(0)
GO
UPDATE CDP
SET BUSINESS_SOURCE =0
WHERE BUSINESS_SOURCE IS NULL
GO
/*** CREATED BY NILESHC ENDS ***/
/*** CREATED BY PREM STARTS ***/
/*** PURPOSE: AWR ST Vehicle Collection ***/
/*** DATE: 13/08/2021 TIME: 16:22 ***/
CREATE TABLE RECEIVABLE_EXECUTIVE_ENTRY (BRANCH_CODE INT DEFAULT(0), USER_CODE CHAR(10) DEFAULT(''))
GO
ALTER TABLE RECEIVABLE_EXECUTIVE_ENTRY
ALTER COLUMN USER_CODE CHAR(10) COLLATE  SQL_LATIN1_GENERAL_CP1_CI_AS
GO
CREATE UNIQUE INDEX BRANCH_CODE_USERS  ON RECEIVABLE_EXECUTIVE_ENTRY(BRANCH_CODE, USER_CODE)
GO
ALTER TABLE DEBITORS_SECTION2
ADD RECEIVABLE_USER CHAR(10) DEFAULT('')
GO
UPDATE DEBITORS_SECTION2
SET RECEIVABLE_USER =''
WHERE RECEIVABLE_USER IS NULL
GO
ALTER TABLE AGREEMENTS_SECTION2
ADD RECEIVABLE_USER CHAR(10) DEFAULT('')
GO
UPDATE AGREEMENTS_SECTION2
SET RECEIVABLE_USER =''
WHERE RECEIVABLE_USER IS NULL
GO
ALTER TABLE AGREEMENTS_SECTION2
ADD FOLLOWUP_DATE CHAR(8) DEFAULT('')
GO
UPDATE AGREEMENTS_SECTION2
SET FOLLOWUP_DATE =''
WHERE FOLLOWUP_DATE IS NULL
GO
ALTER TABLE AGREEMENTS
ADD RECEIVABLE_EMAIL_SENT CHAR(1) DEFAULT('N')
GO
UPDATE AGREEMENTS
SET RECEIVABLE_EMAIL_SENT ='N'
WHERE RECEIVABLE_EMAIL_SENT IS NULL
GO
ALTER TABLE DELIVERY_PICKUP_DETAILS
ADD CLOSING_REASON_CODE SMALLINT DEFAULT(0)
GO
UPDATE DELIVERY_PICKUP_DETAILS
SET CLOSING_REASON_CODE = 0
WHERE CLOSING_REASON_CODE IS NULL
GO
ALTER TABLE AGREEMENTS_SECTION2
ADD CLOSING_REASON_CODE SMALLINT DEFAULT(0)
GO
UPDATE AGREEMENTS_SECTION2
SET CLOSING_REASON_CODE = 0
WHERE CLOSING_REASON_CODE IS NULL
GO
ALTER TABLE AGREEMENTS_SECTION2
ADD FOLLOW_UP_CREATED CHAR(1) DEFAULT('N')
GO
UPDATE AGREEMENTS_SECTION2
SET FOLLOW_UP_CREATED = 'N'
WHERE FOLLOW_UP_CREATED IS NULL
GO
ALTER TABLE INVOICES
ADD AUTHORIZE_YN CHAR(1) DEFAULT('N')
GO
UPDATE INVOICES
SET AUTHORIZE_YN = 'N'
WHERE AUTHORIZE_YN IS NULL
GO
CREATE TABLE INVOICES_AUTHORIZATION (INVOICE_NO FLOAT DEFAULT(0.0), AUTH_DATE CHAR(8) DEFAULT('00000000'), AUTH_TIME INT DEFAULT(0), USER_ID CHAR(10) DEFAULT(''), REMARKS_1 VARCHAR(200) DEFAULT(''), REMARKS_2 VARCHAR(200) DEFAULT(''), AUTHORIZED_YN CHAR(1) DEFAULT('N'))
GO
CREATE INDEX INDX_INVOICES_AUTHORIZATION on INVOICES_AUTHORIZATION (INVOICE_NO)
GO
/***MSSQL***/
/* CREEATED BY DIVYA STARTS */
/* PURPOSE: Massar Delivery Note/Quotation Reference No For Material Screen  AND
Massar Supplier QuotationNo/ Reference No For Purchase Order Screen*/
/* DATE:17/08/2021  TIME:11:02  */
ALTER TABLE GRN_MASTER
ADD DELIVERY_REFERNECE_NO VARCHAR(30) DEFAULT(' ')
GO
UPDATE GRN_MASTER
SET DELIVERY_REFERNECE_NO  = ' '
WHERE DELIVERY_REFERNECE_NO  IS NULL
GO
ALTER TABLE PURCHASE_ORDERMASTER
ADD QUOT_REFERNECE_NO VARCHAR(30) DEFAULT(' ')
GO
UPDATE PURCHASE_ORDERMASTER
SET QUOT_REFERNECE_NO  = ' '
WHERE QUOT_REFERNECE_NO  IS NULL
GO
/* CREATED BY DIVYA END */
/* CREEATED BY SURAJD STARTS */
/* PURPOSE: Vat On Toll Fee-Saas*/
/* DATE:25/08/2021  TIME:19:02  */
ALTER TABLE DEFAULT_CONTROL3
ADD ALLOW_VAT_ON_TOLL_FEE CHAR(1) DEFAULT('N')
GO
UPDATE DEFAULT_CONTROL3
SET ALLOW_VAT_ON_TOLL_FEE=''
WHERE ALLOW_VAT_ON_TOLL_FEE IS NULL
GO
/* CREATED BY SURAJD END */
/*** CREATED BY JAYESH STARTS ***/
/*** PURPOSE: SPR#104769 ***/
/*** DATE: 02/09/2021 TIME: 15:10 PM ***/
ALTER TABLE DEFAULT_CONTROL3
ADD ACC_CHARGEOFF_AMT FLOAT DEFAULT(0.0)
GO
UPDATE DEFAULT_CONTROL3 SET ACC_CHARGEOFF_AMT=0.0 WHERE ACC_CHARGEOFF_AMT IS NULL
GO
/*** CREATED BY JAYESH ENDS***/
/*** CREATED BY HITESH STARTS ***/
/*** PURPOSE: Ford Interface Changes ***/
/*** DATE: 07/09/2021 TIME: 10:30 AM ***/
ALTER TABLE AccInterface_ford
ADD DOCCODE  VARCHAR(20) DEFAULT(' ')
GO
UPDATE AccInterface_ford
SET DOCCODE='' WHERE DOCCODE IS NULL
GO
/*** CREATED BY HITESH ENDS***/
/*** CREEATED BY PRAFULL STARTS ***/
/*** PURPOSE: HERTZ DUBAI  - SUBSCRIPTION MODULE CHANGES***/
/*** DATE: 08/09/2021  TIME:06:15***/
ALTER TABLE DELIVERY_PICKUP_DETAILS
ADD LATITUDE VARCHAR(30) DEFAULT(' ')
GO
UPDATE DELIVERY_PICKUP_DETAILS
SET LATITUDE=' ' WHERE LATITUDE IS NULL
GO
ALTER TABLE DELIVERY_PICKUP_DETAILS
ADD LONGITUDE VARCHAR(30) DEFAULT(' ')
GO
UPDATE DELIVERY_PICKUP_DETAILS
SET LONGITUDE=' ' WHERE LONGITUDE IS NULL
GO
/*** CREEATED BY PRAFULL ENDS ***/
/*** CREATED BY NILESHC STARTS ***/
/*** PURPOSE: RENTAL QUOTATION RATE SHOP ***/
/*** DATE: 17/09/2021 TIME: 11:00 PM ***/
ALTER TABLE PRICE_CALCULATIONOPEL
ADD RATE_SR_NO SMALLINT DEFAULT(0)
GO
UPDATE PRICE_CALCULATIONOPEL
SET RATE_SR_NO =0
WHERE RATE_SR_NO IS NULL
GO
/*** CREATED BY NILESHC ENDS ***/
/*** CREATED BY NILESHC STARTS ***/
/*** PURPOSE: THRIFTY QUOTATION RATE SHOP ***/
/*** DATE: 20/09/2021 TIME: 10:10 PM ***/
ALTER TABLE PRICE_CALCULATIONOPEL
ADD BUSINESS_SOURCE_CODE SMALLINT DEFAULT(0)
GO
UPDATE PRICE_CALCULATIONOPEL
SET BUSINESS_SOURCE_CODE =0
WHERE BUSINESS_SOURCE_CODE IS NULL
GO
/*** CREATED BY NILESHC ENDS ***/
/*** CREATED BY NILESHC STARTS ***/
/*** PURPOSE: THRIFTY SA CROSS BORDER COUNTRIES FOR QUOTATION ***/
/*** DATE: 21/09/2021 TIME: 01:10 PM ***/
ALTER TABLE AGR_CROSS_BORDER_COUNTRY
ADD QUOTATION_NO CHAR(12) DEFAULT(' ')
GO
UPDATE AGR_CROSS_BORDER_COUNTRY
SET QUOTATION_NO = ' '
WHERE QUOTATION_NO IS NULL
GO
/*** CREATED BY NILESHC ENDS ***/
/*** CREATED BY HITESH STARTS ***/
/*** PURPOSE: EHI Price Calc Changes ***/
/*** DATE: 21/09/2021 TIME: 18:18 PM ***/
ALTER TABLE AGREEMENTS_SECTION2
ADD AverageDailyRate FLOAT DEFAULT(0)
GO
UPDATE AGREEMENTS_SECTION2
SET AverageDailyRate=0
WHERE AverageDailyRate IS NULL
GO
/*** CREATED BY HITESH ENDS ***/
/*** CREATED BY PREM STARTS ***/
/*** PURPOSE: AWR ST Expo Bookings ***/
/*** DATE: 24/07/2021 TIME: 17:27 ***/
CREATE TABLE FMS_EXPO_BOOKING (RECORD_ID INT, EXPO_BOOKING_ID CHAR(12) DEFAULT(''), VEHICLE_NUMBER CHAR(10) DEFAULT(''), AGREEMENT_NO INT DEFAULT(0), CHECK_OUT_DATE CHAR(8) DEFAULT('00000000'), CHECK_OUT_TIME INT DEFAULT(0), CHECK_IN_DATE CHAR(8) DEFAULT('00000000'), CHECK_IN_TIME INT DEFAULT(0), DRIVER_CODE FLOAT DEFAULT(0), DRIVER_LAST_NAME NVARCHAR(120) DEFAULT(''), DRIVER_FIRST_NAME NVARCHAR(120) DEFAULT(''),
DRIVER_LICENSE_NUMBER NCHAR(40) DEFAULT(''), DRIVER_CONTACT NCHAR(40) DEFAULT(''), TRANSACTION_DATE CHAR(8) DEFAULT('00000000'), STATUS_CODE INT DEFAULT(0))
GO
ALTER TABLE FMS_EXPO_BOOKING
ADD DRIVER_LICENSE NCHAR(40) DEFAULT('')
GO
UPDATE FMS_EXPO_BOOKING
SET DRIVER_LICENSE = ''
WHERE DRIVER_LICENSE IS NULL
GO
ALTER TABLE FMS_EXPO_BOOKING
ADD CHECK_OUT_FUEL SMALLINT DEFAULT(0)
GO
UPDATE FMS_EXPO_BOOKING
SET CHECK_OUT_FUEL = 0
WHERE CHECK_OUT_FUEL IS NULL
GO
ALTER TABLE FMS_EXPO_BOOKING
ADD CHECK_IN_FUEL SMALLINT DEFAULT(0)
GO
UPDATE FMS_EXPO_BOOKING
SET CHECK_IN_FUEL = 0
WHERE CHECK_IN_FUEL IS NULL
GO
ALTER TABLE FMS_EXPO_BOOKING
ADD CHECK_OUT_KM INT DEFAULT(0)
GO
UPDATE FMS_EXPO_BOOKING
SET CHECK_OUT_KM = 0
WHERE CHECK_OUT_KM IS NULL
GO
ALTER TABLE FMS_EXPO_BOOKING
ADD CHECK_IN_KM INT DEFAULT(0)
GO
UPDATE FMS_EXPO_BOOKING
SET CHECK_IN_KM = 0
WHERE CHECK_IN_KM IS NULL
GO
CREATE INDEX FMS_EXPO_BOOKING_INDX on FMS_EXPO_BOOKING(RECORD_ID)
GO
ALTER TABLE DEBITORS_SECTION2
ADD PAY_EXPO_BOOKINGS CHAR(1) DEFAULT('N')
GO
UPDATE DEBITORS_SECTION2
SET PAY_EXPO_BOOKINGS = 'N'
WHERE PAY_EXPO_BOOKINGS IS NULL
GO
ALTER TABLE TRAFFIC_TICKETS
ADD EXPO_BOOKING_ID CHAR(12) DEFAULT('')
GO
UPDATE TRAFFIC_TICKETS
SET EXPO_BOOKING_ID = ''
WHERE EXPO_BOOKING_ID IS NULL
GO
ALTER TABLE AGREEMENT_DRIVER_HISTORY
ADD EXPO_BOOKING_ID CHAR(12) DEFAULT('')
GO
UPDATE AGREEMENT_DRIVER_HISTORY
SET EXPO_BOOKING_ID = ''
WHERE EXPO_BOOKING_ID IS NULL
GO
ALTER TABLE INCIDENT_INFORMATION
ADD EXPO_BOOKING_ID CHAR(12) DEFAULT('')
GO
UPDATE INCIDENT_INFORMATION
SET EXPO_BOOKING_ID = ''
WHERE EXPO_BOOKING_ID IS NULL
GO
/*** CREATED BY PREM SCRIPT ENDS ***/
/*** CREATED BY PREM STARTS ***/
/*** PURPOSE: AWR ST Reservation ***/
/*** DATE: 24/07/2021 TIME: 17:27 ***/
ALTER TABLE DEAL
ADD RENTAL_QUOTATION CHAR(12) DEFAULT('')
GO
UPDATE DEAL
SET RENTAL_QUOTATION=''
WHERE RENTAL_QUOTATION IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD RECEIVABLE_USER CHAR(10) DEFAULT('')
GO
UPDATE RESERVATION_SEC2
SET RECEIVABLE_USER =''
WHERE RECEIVABLE_USER IS NULL
GO
ALTER TABLE SUBAGREEMENTS
ADD DELIVERY_YN CHAR(1) DEFAULT('N')
GO
UPDATE SUBAGREEMENTS
SET DELIVERY_YN = 'N'
WHERE DELIVERY_YN IS NULL
GO
CREATE TABLE DISTANCE_PKG (FROM_LOCATION INT DEFAULT(0), TO_LOCATION INT DEFAULT(0), PACKAGE_CODE CHAR(3) DEFAULT(''), CHARGE_PRICE FLOAT DEFAULT(0.0))
GO
CREATE UNIQUE INDEX DISTANCE_PKG_FROMTOPKG ON DISTANCE_PKG (FROM_LOCATION, TO_LOCATION, PACKAGE_CODE)
GO
CREATE TABLE PREPAID_POLICY (POLICY_CODE INT DEFAULT(0), DEALER_CODE INT DEFAULT(0), DRIVER_CODE FLOAT DEFAULT(0), DEBITOR_CODE INT DEFAULT(0), CDP_CODE CHAR(9) DEFAULT(''), DRIVER_LAST_NAME NVARCHAR(60) DEFAULT(''), DRIVER_FIRST_NAME NVARCHAR(60) DEFAULT(''), FREE_DAYS INT DEFAULT(0), CONSUME_DAYS INT DEFAULT(0), DISCOUNT_PERC FLOAT DEFAULT(0.0), DISCOUNT_AMOUNT FLOAT DEFAULT(0.0), POLICY_INS_DATE_FROM CHAR(8) DEFAULT('00000000'), POLICY_INS_DATE_TO CHAR(8) DEFAULT('00000000'), POLICY_STATUS INT DEFAULT(0), CREATED_DATE CHAR(8) DEFAULT('00000000'), CREATED_TIME INT DEFAULT(0), CREATED_BY CHAR(10) DEFAULT(''), LAST_DOCUMENT_NO INT DEFAULT(0))
GO
CREATE UNIQUE INDEX PREPAID_POLICY_INDX ON PREPAID_POLICY (POLICY_CODE)
GO
ALTER TABLE AGREEMENTS
ADD POLICY_CODE INT DEFAULT(0)
GO
UPDATE AGREEMENTS
SET POLICY_CODE = 0
WHERE POLICY_CODE IS NULL
GO
/*** CREATED BY PREM SCRIPT ENDS ***/
/*** CREATED BY HITESH STARTS ***/
/*** PURPOSE: Batch Changes ***/
/*** DATE: 28/09/2021 TIME: 18:18 PM ***/
CREATE TABLE BATCH_USER_TIMING
(
TUSR CHAR(10) DEFAULT(' '),
FROM_TIME INTEGER DEFAULT(0),
TO_TIME INTEGER DEFAULT(0)
)
GO
CREATE UNIQUE INDEX IDX_BATCH_TIME ON BATCH_USER_TIMING(TUSR)
GO
/*** CREATED BY HITESH ENDS ***/
/*** CREATED BY NILESHC STARTS ***/
/*** PURPOSE: VWFS Storefront  ***/
/*** DATE: 20/10/2021 TIME: 11:40 PM ***/
ALTER TABLE RES_IMPORT_NATIONAL
ADD TITLE VARCHAR(35) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET TITLE=' '
WHERE TITLE IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD TITLE VARCHAR(35) DEFAULT(' ')
GO
UPDATE RESERVATION_SEC2
SET TITLE=' '
WHERE TITLE IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD VERIMILID VARCHAR(100) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET VERIMILID=' '
WHERE VERIMILID IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD VERIMILID VARCHAR(35) DEFAULT(' ')
GO
UPDATE RESERVATION_SEC2
SET VERIMILID=' '
WHERE VERIMILID IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD PAY_SERIES_ID VARCHAR(50) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET PAY_SERIES_ID=' '
WHERE PAY_SERIES_ID IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD PAY_SERIES_ID VARCHAR(35) DEFAULT(' ')
GO
UPDATE RESERVATION_SEC2
SET PAY_SERIES_ID=' '
WHERE PAY_SERIES_ID IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD DISTRIBUTION_AMOUNT FLOAT DEFAULT(0)
GO
UPDATE RES_IMPORT_NATIONAL SET DISTRIBUTION_AMOUNT=0
WHERE DISTRIBUTION_AMOUNT IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD DISTRIBUTION_AMOUNT FLOAT DEFAULT(0)
GO
UPDATE RESERVATION_SEC2
SET DISTRIBUTION_AMOUNT=0
WHERE DISTRIBUTION_AMOUNT IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD PRODUCT_RENTAL_LEASE CHAR(10) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET PRODUCT_RENTAL_LEASE=' '
WHERE PRODUCT_RENTAL_LEASE IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD PRODUCT_RENTAL_LEASE CHAR(10) DEFAULT(' ')
GO
UPDATE RESERVATION_SEC2
SET PRODUCT_RENTAL_LEASE=' '
WHERE PRODUCT_RENTAL_LEASE IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD MIN_DURATION SMALLINT DEFAULT(0)
GO
UPDATE RES_IMPORT_NATIONAL
SET MIN_DURATION=0
WHERE MIN_DURATION IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD MIN_DURATION SMALLINT DEFAULT(0)
GO
UPDATE RESERVATION_SEC2
SET MIN_DURATION=0
WHERE MIN_DURATION IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD MAX_DURATION SMALLINT DEFAULT(0)
GO
UPDATE RES_IMPORT_NATIONAL
SET MAX_DURATION=0
WHERE MAX_DURATION IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD MAX_DURATION SMALLINT DEFAULT(0)
GO
UPDATE RESERVATION_SEC2
SET MAX_DURATION=0
WHERE MAX_DURATION IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD DURATION_UNIT CHAR(10) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET DURATION_UNIT=' '
WHERE DURATION_UNIT IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD DURATION_UNIT CHAR(10) DEFAULT(' ')
GO
UPDATE RESERVATION_SEC2
SET DURATION_UNIT=' '
WHERE DURATION_UNIT IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD MONTHLY_MILEAGE INTEGER DEFAULT(0)
GO
UPDATE RES_IMPORT_NATIONAL
SET MONTHLY_MILEAGE=0
WHERE MONTHLY_MILEAGE IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD MONTHLY_MILEAGE INTEGER DEFAULT(0)
GO
UPDATE RESERVATION_SEC2
SET MONTHLY_MILEAGE=0
WHERE MONTHLY_MILEAGE IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD MILEAGE_UNIT CHAR(10) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET MILEAGE_UNIT=' '
WHERE MILEAGE_UNIT IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD MILEAGE_UNIT CHAR(10) DEFAULT(' ')
GO
UPDATE RESERVATION_SEC2
SET MILEAGE_UNIT=' '
WHERE MILEAGE_UNIT IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD MONTHLY_RATE_AMOUNT FLOAT DEFAULT(0)
GO
UPDATE RES_IMPORT_NATIONAL
SET MONTHLY_RATE_AMOUNT=0
WHERE MONTHLY_RATE_AMOUNT IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD MONTHLY_RATE_AMOUNT FLOAT DEFAULT(0)
GO
UPDATE RESERVATION_SEC2
SET MONTHLY_RATE_AMOUNT=0
WHERE MONTHLY_RATE_AMOUNT IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD MON_TOTAL_RATE_AMOUNT FLOAT DEFAULT(0)
GO
UPDATE RES_IMPORT_NATIONAL
SET MON_TOTAL_RATE_AMOUNT=0
WHERE MON_TOTAL_RATE_AMOUNT IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD MON_TOTAL_RATE_AMOUNT FLOAT DEFAULT(0)
GO
UPDATE RESERVATION_SEC2
SET MON_TOTAL_RATE_AMOUNT=0
WHERE MON_TOTAL_RATE_AMOUNT IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD EXCESS_MILEAGE_CHARGE FLOAT DEFAULT(0)
GO
UPDATE RES_IMPORT_NATIONAL
SET EXCESS_MILEAGE_CHARGE=0
WHERE EXCESS_MILEAGE_CHARGE IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD EXCESS_MILEAGE_CHARGE FLOAT DEFAULT(0)
GO
UPDATE RESERVATION_SEC2
SET EXCESS_MILEAGE_CHARGE=0
WHERE EXCESS_MILEAGE_CHARGE IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD SERVICE_PACKAGE_COST FLOAT DEFAULT(0)
GO
UPDATE RES_IMPORT_NATIONAL
SET SERVICE_PACKAGE_COST=0
WHERE SERVICE_PACKAGE_COST IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD SERVICE_PACKAGE_COST FLOAT DEFAULT(0)
GO
UPDATE RESERVATION_SEC2
SET SERVICE_PACKAGE_COST=0
WHERE SERVICE_PACKAGE_COST IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD FROMSUBSCRIPTION CHAR(1) DEFAULT('N')
GO
UPDATE RES_IMPORT_NATIONAL
SET FROMSUBSCRIPTION ='N'
WHERE FROMSUBSCRIPTION IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD DEL_HOUSE_NO VARCHAR(20) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET DEL_HOUSE_NO=' '
WHERE DEL_HOUSE_NO IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD PICKUP_HOUSE_NO VARCHAR(20) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET PICKUP_HOUSE_NO=' '
WHERE PICKUP_HOUSE_NO IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD DEL_COUNTRY_CODE VARCHAR(10) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET DEL_COUNTRY_CODE=' '
WHERE DEL_COUNTRY_CODE IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD PICKUP_COUNTRY_CODE VARCHAR(10) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET PICKUP_COUNTRY_CODE=' '
WHERE PICKUP_COUNTRY_CODE IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD DEL_LATITUDE VARCHAR(20) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET DEL_LATITUDE=' '
WHERE DEL_LATITUDE IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD DEL_LONGITUDE VARCHAR(20) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET DEL_LONGITUDE=' '
WHERE DEL_LONGITUDE IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD PICKUP_LATITUDE VARCHAR(20) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET PICKUP_LATITUDE=' '
WHERE PICKUP_LATITUDE IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD PICKUP_LONGITUDE VARCHAR(20) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET PICKUP_LONGITUDE=' '
WHERE PICKUP_LONGITUDE IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD NATIONALITY VARCHAR(30) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET NATIONALITY =' '
WHERE NATIONALITY IS NULL
GO
ALTER TABLE RESERVATION_SEC2
ADD NATIONALITY SMALLINT DEFAULT(0)
GO
UPDATE RESERVATION_SEC2
SET NATIONALITY =0
WHERE NATIONALITY IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD IBAN VARCHAR(50) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET IBAN=' '
WHERE IBAN IS NULL
GO
ALTER TABLE RES_IMPORT_NATIONAL
ADD BIC_CODE VARCHAR(50) DEFAULT(' ')
GO
UPDATE RES_IMPORT_NATIONAL
SET BIC_CODE=' '
WHERE BIC_CODE IS NULL
GO
/*** CREATED BY NILESHC ENDS ***/
/*** CREATED BY NILESHC STARTS ***/
/*** PURPOSE: INTERFACE IDENTIFICATION THRIFTY SA/NAMIBIA ***/
/*** DATE: 26/10/2021 TIME: 05:10 PM ***/
ALTER TABLE DEF_ADDITIONAL_FLAGS
ADD CREDIT_LIMIT_DAYS SMALLINT DEFAULT(0)
GO
UPDATE DEF_ADDITIONAL_FLAGS
SET CREDIT_LIMIT_DAYS =0
WHERE CREDIT_LIMIT_DAYS IS NULL
GO
/*** CREATED BY NILESHC ENDS ***/
/***CREATED BY JAYESH STARTS ***/
/***DATE: 28/10/2021 TIME: 17:10 PM***/
/*** PURPOSE: SPR # 104789***/
ALTER TABLE CAR_CONTROL
ADD OPERATIONAL_CARD_NO VARCHAR(20) DEFAULT('')
GO
UPDATE CAR_CONTROL SET OPERATIONAL_CARD_NO =''
WHERE OPERATIONAL_CARD_NO IS NULL
GO
ALTER TABLE CAR_CONTROL
ADD OPERATIONAL_CARD_EXPDATE CHAR(8) DEFAULT('00000000')
GO
UPDATE CAR_CONTROL SET OPERATIONAL_CARD_EXPDATE ='00000000'
WHERE OPERATIONAL_CARD_EXPDATE IS NULL
GO
/***CREATED BY JAYESH ENDS ***/

/*** INSERT RECORD INTO VERSION CONTROL VERSION XL 1.10 SP5 START***/
INSERT INTO VERSION_CONTROL VALUES (0,'XL 1.10 SP5','20210813',750,CONVERT (CHAR(8),GETDATE(),112),' ')
GO
/***SCRIPT 750 ENDS HERE  ***/